"""Tests for src.phase4_gridsearch.

Most outcome-based assertions skip if the gridsearch hasn't been run yet
(the result CSVs are gitignored and regenerated by
`python -m src.phase4_gridsearch`)."""
from __future__ import annotations

import pandas as pd
import pytest

from src import phase4_gridsearch as p4
from src.text_clean import STOPWORDS_FOR_VECTORIZER, vectorizer_preprocessor


# ---------- Pipeline construction (no compute) ----------

def test_logreg_pipeline_uses_shared_stopwords_and_preprocessor():
    pipe = p4.make_logreg_pipeline()
    vec = pipe.named_steps["vect"]
    clf = pipe.named_steps["clf"]
    assert vec.stop_words is STOPWORDS_FOR_VECTORIZER
    assert vec.preprocessor is vectorizer_preprocessor
    # liblinear handles both L1 and L2; required for the cross-penalty grid
    assert clf.solver == "liblinear"
    assert clf.class_weight == "balanced"
    assert clf.random_state == p4.RANDOM_STATE


def test_svm_pipeline_uses_shared_stopwords_and_preprocessor():
    pipe = p4.make_svm_pipeline()
    vec = pipe.named_steps["vect"]
    clf = pipe.named_steps["clf"]
    assert vec.stop_words is STOPWORDS_FOR_VECTORIZER
    assert vec.preprocessor is vectorizer_preprocessor
    assert clf.class_weight == "balanced"
    assert clf.random_state == p4.RANDOM_STATE


def test_rf_pipeline_inherits_stage_4a_vectorizer_params():
    best_vec_params = {
        "vect__min_df": 2,
        "vect__max_df": 0.9,
        "vect__ngram_range": (1, 2),
    }
    pipe = p4.make_rf_pipeline_with_fixed_vectorizer(best_vec_params)
    vec = pipe.named_steps["vect"]
    assert vec.min_df == 2
    assert vec.max_df == 0.9
    assert vec.ngram_range == (1, 2)
    assert vec.stop_words is STOPWORDS_FOR_VECTORIZER
    assert vec.preprocessor is vectorizer_preprocessor


def test_vectorizer_grid_has_expected_size():
    """2 min_df × 2 max_df × 3 ngram = 12 vectorizer settings."""
    grid = p4.VECTORIZER_GRID
    n = (
        len(grid["vect__min_df"])
        * len(grid["vect__max_df"])
        * len(grid["vect__ngram_range"])
    )
    assert n == 12


# ---------- Output CSV shape (require run) ----------

@pytest.fixture
def gridsearch_results():
    if not p4.GRIDSEARCH_RESULTS_PATH.exists():
        pytest.skip("gridsearch_results.csv missing — run `python -m src.phase4_gridsearch`")
    return pd.read_csv(p4.GRIDSEARCH_RESULTS_PATH)


def test_gridsearch_results_includes_all_three_models(gridsearch_results):
    assert set(gridsearch_results["model"]) == {"logreg", "linear_svc", "random_forest"}


def test_gridsearch_results_logreg_row_count(gridsearch_results):
    """LogReg: 12 vec × 5 C × 2 l1_ratio (= L1+L2 corners) = 120 settings."""
    n = (gridsearch_results["model"] == "logreg").sum()
    assert n == 120, f"Expected 120 LogReg rows, got {n}"


def test_gridsearch_results_svm_row_count(gridsearch_results):
    """SVM: 12 vec × 4 C = 48 settings."""
    n = (gridsearch_results["model"] == "linear_svc").sum()
    assert n == 48, f"Expected 48 SVM rows, got {n}"


def test_gridsearch_results_rf_row_count(gridsearch_results):
    """RF: 3 × 3 × 3 = 27 settings."""
    n = (gridsearch_results["model"] == "random_forest").sum()
    assert n == 27, f"Expected 27 RF rows, got {n}"


def test_gridsearch_no_anti_predictive_combo(gridsearch_results):
    """Mean CV AUC < 0.5 means something is mechanically wrong."""
    bad = gridsearch_results[gridsearch_results["mean_test_score"] < 0.5]
    assert bad.empty, (
        f"Combos with CV AUC < 0.5 (anti-predictive): "
        f"{bad[['model', 'params', 'mean_test_score']].to_dict('records')}"
    )


def test_test_eval_has_three_models():
    if not p4.PHASE4_TEST_EVAL_PATH.exists():
        pytest.skip("phase4_test_eval.csv missing")
    eva = pd.read_csv(p4.PHASE4_TEST_EVAL_PATH)
    assert set(eva["model"]) == {"logreg", "linear_svc", "random_forest"}


def test_per_justice_auc_table_present():
    if not p4.PHASE4_PER_JUSTICE_AUC_PATH.exists():
        pytest.skip("phase4_per_justice_auc.csv missing")
    auc = pd.read_csv(p4.PHASE4_PER_JUSTICE_AUC_PATH)
    # Should have a row per Justice in the test set (could be < 16 if some
    # Justices had zero test rows in fold 0)
    assert len(auc) >= 10, f"Expected ≥10 Justices in per-Justice AUC; got {len(auc)}"
    # Bootstrap CIs should be present for at least the larger Justices
    has_ci = auc["ci_lo_95"].notna().sum()
    assert has_ci >= 5, f"Expected ≥5 Justices with bootstrap CIs; got {has_ci}"
