"""Tests for src.compute_embeddings.

Most tests skip if the embeddings haven't been encoded yet (the .npy
files are gitignored and regenerated by `python -m src.compute_embeddings`)."""
from __future__ import annotations

import numpy as np
import pandas as pd
import pytest

from src import compute_embeddings as ce


def test_models_dict_contents():
    assert set(ce.MODELS) == {"minilm", "mpnet"}
    assert ce.MODELS["minilm"] == ("all-MiniLM-L6-v2", 384)
    assert ce.MODELS["mpnet"] == ("all-mpnet-base-v2", 768)


def test_device_is_cpu():
    """cai-plan: CPU build only, no GPU dependency."""
    assert ce.DEVICE == "cpu"


def test_matches_cache_returns_false_when_missing(tmp_path):
    fake = tmp_path / "missing.npy"
    assert ce._matches_cache(fake, (5, 384)) is False


def test_matches_cache_returns_true_on_shape_match(tmp_path):
    p = tmp_path / "ok.npy"
    np.save(p, np.zeros((5, 384), dtype=np.float32))
    assert ce._matches_cache(p, (5, 384)) is True


def test_matches_cache_returns_false_on_shape_mismatch(tmp_path):
    p = tmp_path / "bad.npy"
    np.save(p, np.zeros((5, 768), dtype=np.float32))
    assert ce._matches_cache(p, (5, 384)) is False


# ----- Cached-output checks (require encoding to have run) -----

@pytest.fixture
def modeling_table():
    return pd.read_parquet(ce.MODELING_TABLE_PATH)


def test_minilm_cache_shape(modeling_table):
    p = ce._cache_path("minilm")
    if not p.exists():
        pytest.skip("minilm cache missing — run `python -m src.compute_embeddings`")
    arr = np.load(p)
    assert arr.shape == (len(modeling_table), 384)
    assert arr.dtype == np.float32


def test_mpnet_cache_shape(modeling_table):
    p = ce._cache_path("mpnet")
    if not p.exists():
        pytest.skip("mpnet cache missing — run `python -m src.compute_embeddings`")
    arr = np.load(p)
    assert arr.shape == (len(modeling_table), 768)
    assert arr.dtype == np.float32


def test_row_index_aligned_to_modeling_table(modeling_table):
    """Critical: the embedding row index MUST match modeling_table row order
    so positional split indices from get_train_test_split() are valid."""
    if not ce.ROW_INDEX_PATH.exists():
        pytest.skip("row_index.parquet missing")
    idx = pd.read_parquet(ce.ROW_INDEX_PATH)
    assert len(idx) == len(modeling_table)
    assert (idx["caseId"].values == modeling_table["caseId"].values).all()
    assert (idx["oyez_identifier"].values == modeling_table["oyez_identifier"].values).all()


def test_load_embeddings_returns_aligned_data():
    if not ce._cache_path("minilm").exists():
        pytest.skip("minilm cache missing")
    arr, idx = ce.load_embeddings("minilm")
    assert len(arr) == len(idx)
    assert arr.shape[1] == 384


def test_embeddings_are_finite_and_not_constant():
    """Sanity: no NaN/Inf, and the encoder isn't returning a constant vector."""
    if not ce._cache_path("minilm").exists():
        pytest.skip("minilm cache missing")
    arr, _ = ce.load_embeddings("minilm")
    assert np.isfinite(arr).all(), "Embeddings contain NaN/Inf"
    assert arr.std() > 0.001, "Embeddings have near-zero variance — encoder broken?"
