"""Tests for src.phase3_baseline_sweep — baseline-sweep mechanics + outputs.

Most tests are skipped if the sweep hasn't been run (the result CSVs are
gitignored and regenerated by `python -m src.phase3_baseline_sweep`).
"""
from __future__ import annotations

import numpy as np
import pandas as pd
import pytest
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.model_selection import StratifiedGroupKFold

from src import phase3_baseline_sweep as p3
from src.text_clean import STOPWORDS_FOR_VECTORIZER


# ---------- Pipeline construction ----------

def test_all_three_vectorizers_use_custom_stopwords():
    """Non-Negotiable #3: all three vectorizers consume STOPWORDS_FOR_VECTORIZER."""
    vecs = p3.make_vectorizers()
    assert set(vecs) == {"bow_unigram", "tfidf_unigram", "tfidf_bigram"}
    for name, v in vecs.items():
        assert v.stop_words is STOPWORDS_FOR_VECTORIZER, (
            f"{name} doesn't pass STOPWORDS_FOR_VECTORIZER as stop_words"
        )


def test_classifier_set_is_logreg_svc_rf():
    clfs = p3.make_classifiers()
    assert set(clfs) == {"logreg", "linear_svc", "random_forest"}


def test_is_linear_combo():
    assert p3.is_linear_combo("logreg")
    assert p3.is_linear_combo("linear_svc")
    assert not p3.is_linear_combo("random_forest")


# ---------- Split mechanics (Non-Negotiable #1) ----------

def test_stratified_group_split_has_no_case_leakage():
    """Train and test must not share any caseId."""
    df = pd.read_parquet(p3.MODELING_TABLE_PATH).reset_index(drop=True)
    y = df["voted_petitioner"].astype(int).values
    groups = df["caseId"].values

    sgkf = StratifiedGroupKFold(n_splits=5, shuffle=True, random_state=p3.RANDOM_STATE)
    splits = list(sgkf.split(df["text"], y, groups=groups))
    train_idx, test_idx = splits[0][0], splits[0][1]

    train_cases = set(df.iloc[train_idx]["caseId"])
    test_cases = set(df.iloc[test_idx]["caseId"])
    assert not (train_cases & test_cases), (
        f"Case-id leakage: {len(train_cases & test_cases)} overlapping caseIds"
    )


def test_random_state_is_42():
    """Reproducibility: Non-Negotiable #5."""
    assert p3.RANDOM_STATE == 42


# ---------- Output CSVs (require sweep to have run) ----------

@pytest.fixture
def baseline_results():
    if not p3.BASELINE_RESULTS_PATH.exists():
        pytest.skip("baseline_results.csv missing — run `python -m src.phase3_baseline_sweep`")
    return pd.read_csv(p3.BASELINE_RESULTS_PATH)


def test_baseline_results_has_9_rows(baseline_results):
    assert len(baseline_results) == 9, (
        f"Expected 9 (3 vectorizers × 3 classifiers); got {len(baseline_results)}"
    )


def test_baseline_results_metrics_in_valid_ranges(baseline_results):
    for col in ["accuracy", "balanced_accuracy", "precision", "recall", "f1", "roc_auc"]:
        assert (baseline_results[col] >= 0).all() and (baseline_results[col] <= 1).all(), (
            f"{col} out of [0,1]"
        )


def test_no_combo_is_anti_predictive(baseline_results):
    """The right mechanical-correctness check: ROC AUC must be >= 0.5 (random).

    Note: raw accuracy below the 62.4% global majority baseline is EXPECTED
    behavior for `class_weight='balanced'` linear models — they trade
    majority-class accuracy for class-balanced predictions. The cai-plan's
    "below baseline = bug" check applies to unweighted models; we use
    class_weight='balanced' per Non-Negotiable #6."""
    bad = baseline_results[baseline_results["roc_auc"] < 0.5]
    assert bad.empty, (
        f"Combos with ROC AUC < 0.5 (anti-predictive): "
        f"{bad[['combo_id', 'roc_auc']].to_dict('records')}"
    )


def test_per_justice_lift_includes_all_16_justices():
    if not p3.PER_JUSTICE_LIFT_PATH.exists():
        pytest.skip("per_justice_lift.csv missing")
    lift = pd.read_csv(p3.PER_JUSTICE_LIFT_PATH)
    # 16 Justices × 9 combos = 144 rows expected (some Justices may have 0 test rows)
    n_justices = lift["oyez_identifier"].nunique()
    assert n_justices >= 14, (
        f"Expected ≥14 of 16 Justices in per-Justice lift table; got {n_justices}"
    )


def test_top_features_csv_has_60_rows():
    if not p3.TOP_FEATURES_PATH.exists():
        pytest.skip("top_features_best_linear.csv missing")
    feats = pd.read_csv(p3.TOP_FEATURES_PATH)
    assert len(feats) == 60, f"Expected 60 (top 30 ± each); got {len(feats)}"
    # 30 each direction
    assert (feats["direction"] == "petitioner (positive)").sum() == 30
    assert (feats["direction"] == "respondent (negative)").sum() == 30
