"""Generate the Phase 1 Checkpoint 1 numbers and write a markdown summary.

Reads from the cached SCDB, the bulk-fetch log, and the joined parquet.
Writes reports/checkpoint1_summary.md (committed) for paste-ready handoff.
CRISP-DM phase: Data Understanding.
Phase 1 detailed report on coverage, Justice mapping, and joined-table shape.
"""
from __future__ import annotations

import json
import logging
from pathlib import Path

import pandas as pd

from src import fetch_scdb

PARQUET_PATH = Path("data/processed/justice_case_rows.parquet")
JUSTICE_ID_MAP_PATH = Path("data/processed/justice_id_map.csv")
BULK_FETCH_LOG_PATH = Path("reports/results/bulk_fetch_log.csv")
OYEZ_CASES_DIR = Path("data/raw/oyez/cases")
OYEZ_TRANSCRIPTS_DIR = Path("data/raw/oyez/transcripts")
OUT_PATH = Path("reports/checkpoint1_summary.md")

WINDOW_START = 2005
WINDOW_END = 2024

logger = logging.getLogger(__name__)


def _section(title: str) -> str:
    return f"\n## {title}\n\n"


def main() -> None:
    logging.basicConfig(level=logging.INFO,
                        format="%(asctime)s %(levelname)s: %(message)s")

    scdb = fetch_scdb.load_scdb()
    id_map = pd.read_csv(JUSTICE_ID_MAP_PATH)
    fetch_log = pd.read_csv(BULK_FETCH_LOG_PATH) if BULK_FETCH_LOG_PATH.exists() else pd.DataFrame()
    rows = pd.read_parquet(PARQUET_PATH) if PARQUET_PATH.exists() else pd.DataFrame()

    parts = ["# JusticeCast — Phase 1 Checkpoint 1 Summary\n",
             f"_Generated by `src/checkpoint1_analysis.py`. Window: "
             f"{WINDOW_START}–{WINDOW_END}._\n"]

    # ---- Pipeline stages ----
    window = scdb[(scdb.term >= WINDOW_START) & (scdb.term <= WINDOW_END)].copy()
    n_scdb_rows = len(window)
    n_scdb_cases = window["caseId"].nunique()
    n_unique_keys = window.groupby(["term", "docket"]).ngroups

    n_attempted = len(fetch_log)
    n_step1_ok = int(fetch_log["case_fetched"].sum()) if not fetch_log.empty else 0
    n_with_audio = int((fetch_log["n_audio_sessions"] > 0).sum()) if not fetch_log.empty else 0
    n_step2_ok = int(fetch_log["transcripts_fetched"].sum()) if not fetch_log.empty else 0
    n_failed = int((fetch_log["error"].fillna("").astype(str).str.len() > 0).sum()) if not fetch_log.empty else 0

    n_joined_rows = len(rows)
    n_joined_cases = rows["caseId"].nunique() if not rows.empty else 0

    parts.append(_section("Pipeline stages"))
    parts.append(
        "| Stage                                                  | Count |\n"
        "| ------------------------------------------------------ | ----: |\n"
        f"| SCDB Justice-vote rows in {WINDOW_START}–{WINDOW_END} window     | {n_scdb_rows:,} |\n"
        f"| Unique SCDB caseIds in window                          | {n_scdb_cases:,} |\n"
        f"| Unique `(term, docket)` pairs to fetch                 | {n_unique_keys:,} |\n"
        f"| Cases attempted in bulk fetch                          | {n_attempted:,} |\n"
        f"| Step 1 (case metadata) fetched OK                      | {n_step1_ok:,} |\n"
        f"| Cases with ≥1 oral_argument_audio entry                | {n_with_audio:,} |\n"
        f"| Step 2 transcripts fetched (across all audio sessions) | {n_step2_ok:,} |\n"
        f"| Bulk-fetch errors (Step 1 failures)                    | {n_failed:,} |\n"
        f"| Final joined `(case, Justice)` rows in parquet         | {n_joined_rows:,} |\n"
        f"| Distinct cases represented in parquet                  | {n_joined_cases:,} |\n"
    )

    # ---- Justice coverage cross-check ----
    parts.append(_section("Justice coverage cross-check"))
    coverage = []
    for _, jrow in id_map.iterrows():
        jid = jrow["scdb_justice_id"]
        jname = jrow["scdb_justice_name"]
        oyez = jrow["oyez_identifier"]
        scdb_window = window[window["justice"] == jid]
        expected_cases = scdb_window["caseId"].nunique()
        if not rows.empty:
            actual = rows[rows["oyez_identifier"] == oyez]
            actual_rows = len(actual)
            actual_cases = actual["caseId"].nunique()
        else:
            actual_rows = actual_cases = 0
        ratio = (actual_cases / expected_cases) if expected_cases else 0.0
        flag = ""
        if expected_cases >= 50 and actual_cases == 0:
            flag = "⚠️ ZERO — slug almost certainly wrong"
        elif expected_cases >= 50 and ratio < 0.05:
            flag = "⚠️ near-zero ratio — slug likely wrong"
        coverage.append({
            "oyez_identifier": oyez,
            "scdb_name": jname,
            "scdb_id": jid,
            "expected_cases": expected_cases,
            "actual_cases": actual_cases,
            "actual_rows": actual_rows,
            "ratio": ratio,
            "flag": flag,
        })
    cov = pd.DataFrame(coverage).sort_values("scdb_id")

    parts.append("Expected = unique SCDB cases for that Justice within the "
                 "window. Actual = unique cases in the parquet (Justice spoke "
                 "during oral argument). Ratio = actual / expected. A near-zero "
                 "ratio for a long-tenure Justice strongly suggests a wrong "
                 "Oyez slug in `justice_id_map.csv` — fixable without re-fetch.\n\n")
    parts.append(
        "| oyez_identifier         | SCDB name   | id  | expected_cases | actual_cases | actual_rows | ratio  | flag |\n"
        "| ----------------------- | ----------- | --- | -------------: | -----------: | ----------: | -----: | ---- |\n"
    )
    for _, r in cov.iterrows():
        parts.append(
            f"| {r['oyez_identifier']:<23s} | {r['scdb_name']:<11s} | "
            f"{int(r['scdb_id']):>3d} | {r['expected_cases']:>14,d} | "
            f"{r['actual_cases']:>12,d} | {r['actual_rows']:>11,d} | "
            f"{r['ratio']:.2%} | {r['flag']} |\n"
        )

    # ---- Thomas-specific ----
    if not rows.empty:
        thomas_rows = rows[rows["oyez_identifier"] == "clarence_thomas"]
        thomas_cases = thomas_rows["caseId"].nunique()
        thomas_expected = window[window["justice"] == 108]["caseId"].nunique()
        parts.append(_section("Thomas-specific (drives Phase 2 inclusion decision)"))
        parts.append(
            f"- SCDB cases with Thomas in 2005–2024: **{thomas_expected:,}**\n"
            f"- Cases where Thomas actually spoke (parsed transcripts): **{thomas_cases:,}**\n"
            f"- Speaking rate: **{thomas_cases / thomas_expected:.1%}** of his cases\n"
        )

    # ---- Word counts per Justice ----
    if not rows.empty and "word_count" in rows.columns:
        wc = (
            rows.groupby("oyez_identifier")["word_count"]
                .agg(n_rows="size",
                     p25=lambda s: int(s.quantile(0.25)),
                     median=lambda s: int(s.median()),
                     p75=lambda s: int(s.quantile(0.75)),
                     mean=lambda s: int(s.mean()))
                .reset_index()
                .sort_values("median")
        )
        parts.append(_section("Word counts per Justice (across all their cases)"))
        parts.append(
            "| oyez_identifier         | n_rows | p25 | median | p75  | mean |\n"
            "| ----------------------- | -----: | --: | -----: | ---: | ---: |\n"
        )
        for _, r in wc.iterrows():
            parts.append(
                f"| {r['oyez_identifier']:<23s} | {r['n_rows']:>6,d} | "
                f"{r['p25']:>3,d} | {r['median']:>6,d} | "
                f"{r['p75']:>4,d} | {r['mean']:>4,d} |\n"
            )

    # ---- Label distribution + exclusions ----
    if not rows.empty:
        parts.append(_section("Label distribution"))
        n_total = len(rows)
        n_no_label = int(rows["voted_petitioner"].isna().sum())
        excl_party = int((rows["partyWinning"] == 2).sum())
        excl_majority = int(rows["majority"].isna().sum())
        with_label = rows[rows["voted_petitioner"].notna()]
        n_with_label = len(with_label)
        n_pos = int((with_label["voted_petitioner"] == 1).sum())
        n_neg = int((with_label["voted_petitioner"] == 0).sum())
        pos_rate = n_pos / n_with_label if n_with_label else 0.0

        parts.append(
            f"- Joined rows: **{n_total:,}**\n"
            f"- Rows excluded from labels: **{n_no_label:,}** "
            f"({n_no_label / n_total:.1%})\n"
            f"  - Excluded due to `partyWinning == 2` (unclear winner): {excl_party:,}\n"
            f"  - Excluded due to `majority` NaN (Justice did not participate): {excl_majority:,}\n"
            f"- Rows with valid binary label: **{n_with_label:,}**\n"
            f"  - `voted_petitioner == 1` (with-petitioner): {n_pos:,} ({pos_rate:.1%})\n"
            f"  - `voted_petitioner == 0` (against-petitioner): {n_neg:,} ({1 - pos_rate:.1%})\n"
            f"- Majority-class baseline (predict the more common): **{max(pos_rate, 1 - pos_rate):.1%}**\n"
        )

    # ---- Unanimity ----
    if not rows.empty:
        with_label = rows[rows["voted_petitioner"].notna()]
        n_unanimous = int((with_label["unanimous"] == 1).sum())
        parts.append(_section("Unanimity"))
        parts.append(
            f"- Rows in unanimous cases (`minVotes == 0`): **{n_unanimous:,}** "
            f"({n_unanimous / len(with_label):.1%} of labeled rows)\n"
        )

    # ---- Multi-audio ----
    if not rows.empty:
        case_audio = (
            rows[["caseId", "n_audio_sessions"]]
            .drop_duplicates(subset=["caseId"])
        )
        multi = case_audio[case_audio["n_audio_sessions"] > 1]
        parts.append(_section("Multi-audio cases"))
        parts.append(
            f"- Cases with `n_audio_sessions > 1` (re-arguments etc.): "
            f"**{len(multi):,}**\n"
        )
        if not multi.empty:
            sample = multi.head(10).merge(
                rows[["caseId", "caseName"]].drop_duplicates(subset=["caseId"]),
                on="caseId", how="left",
            )
            parts.append("\nFirst few:\n")
            for _, r in sample.iterrows():
                parts.append(
                    f"- {r['caseId']} ({int(r['n_audio_sessions'])} sessions): "
                    f"{(r['caseName'] or '')[:80]}\n"
                )

    # ---- Bulk-fetch wall-clock ----
    if not fetch_log.empty:
        total_sec = float(fetch_log["elapsed_sec"].sum())
        parts.append(_section("Bulk-fetch wall-clock"))
        parts.append(
            f"- Total elapsed (sum of per-case timings): "
            f"**{total_sec:.0f}s** ({total_sec / 60:.1f} min)\n"
            f"- Mean seconds per case: **{total_sec / len(fetch_log):.2f}s**\n"
        )

    # ---- Duplicate (term, docket) ----
    parts.append(_section("Duplicate `(term, docket)` resolution"))
    parts.append(
        "Investigated at Stop B: the duplicate is **Medellin v. Texas, "
        "term=2007, docket=06-984**. SCDB has two `caseId`s for the same "
        "docket: `2007-026` (merits decision, 3/25/2008, 6-3) and `2007-073` "
        "(per-curiam stay denial, 8/5/2008, 5-4). The Oyez oral argument "
        "transcript belongs to the original merits case. `build_dataset.py` "
        "dedupes SCDB on `(term, docket, justice)` keeping the earliest "
        "`dateDecision`, so each Justice's text is paired with the merits "
        "vote (`2007-026`) and the per-curiam stay denial vote is dropped.\n"
    )

    # ---- Fetch failures ----
    parts.append(_section("Fetch failures"))
    if fetch_log.empty:
        parts.append("- No bulk-fetch log present.\n")
    else:
        failures = fetch_log[fetch_log["error"].fillna("").astype(str).str.len() > 0]
        if failures.empty:
            parts.append("- **None.** All Step 1 fetches succeeded.\n")
        else:
            parts.append(f"- **{len(failures)}** failures:\n")
            for _, r in failures.head(20).iterrows():
                parts.append(f"  - {r['term']}/{r['docket']}: {r['error']}\n")

    # ---- Cache size ----
    cases_files = list(OYEZ_CASES_DIR.glob("*.json"))
    transcripts_files = list(OYEZ_TRANSCRIPTS_DIR.glob("*.json"))
    cases_size = sum(p.stat().st_size for p in cases_files) / 1024**2
    transcripts_size = sum(p.stat().st_size for p in transcripts_files) / 1024**2
    parts.append(_section("Cache footprint"))
    parts.append(
        f"- `data/raw/oyez/cases/`: **{len(cases_files):,}** files, "
        f"**{cases_size:.0f} MB**\n"
        f"- `data/raw/oyez/transcripts/`: **{len(transcripts_files):,}** files, "
        f"**{transcripts_size:.0f} MB**\n"
        f"- Total cache: **{cases_size + transcripts_size:.0f} MB** (gitignored)\n"
    )

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text("".join(parts))
    logger.info("Wrote %s", OUT_PATH)
    print(f"Wrote {OUT_PATH}")


if __name__ == "__main__":
    main()
